### ISSUE TITLE
Data from backend duplicates after connecting

### ISSUE THREAD

**Issue by rexmagnusdavid** [Techno3d/TransitArrivalBoard#3]
It seems that when a connection is established to the Rust WebSocket, various parts of the data are duplicated/cached, creating an infinitely increasing Array.

I've checked the code on the frontend (React.js), and to my knowledge, `setState()` should not leave any duplicates.

https://github.com/Techno3d/TransitArrivalBoard/assets/95447323/d08eac86-4f23-45c0-b81d-40547b3b61f6

**Comment by Techno3d** [comment]
Okay I wrote this code on my phone on the train but it was pretty simple and should work now.

**Comment by rexmagnusdavid** [comment]
Resolved by https://github.com/Techno3d/TransitArrivalBoard/commit/cc4c5957bcdd5660ff01f98361d3f007a1834fa2
