### ISSUE TITLE
A failed API request will result in no data being sent

### ISSUE THREAD

**Issue by rexmagnusdavid** [Techno3d/TransitArrivalBoard#4]
HTTP requests are not always reliable, and there's always a chance for them to not receive any data. Whatever the cause, the result is that the Rust backend will send an empty list ad map of vehicles to the TypeScript frontend. This can cause confusion, since the frontend is fully reliant on the data that it receives without caching. It will believe that no vehicles are scheduled and thus, show "No vehicles scheduled."

Instead, a prediction system should be implemented to predict the times of trains currently listed in the data if the HTTP request fails. For example, if a train was supposed to arrive in 5 minutes and the latest HTTP request fails, then the system should set the arrival time to 4 minutes. Once a train goes from 0 to -1 minutes, it will be removed.

**Comment by rexmagnusdavid** [comment]
This is actually not a bug, since the program works as intended, and no errors occur. This feature is meant to avoid confusion in the event that the API fails to return data.

**Comment by Techno3d** [comment]
Can we just rerun the http request?

**Comment by rexmagnusdavid** [comment]
> Can we just rerun the http request?

I guess a compromise would be to retry maybe 1 to 3 more times before falling back to the prediction system. I'm still worried that a period of bad internet connections could still occur, which would still give a confusing sight for anyone trying to find the latest times.

Another potential solution is to decrease the refresh delay. I'm not sure what the rate limit is, but surely other transit apps have managed to solve this issue.

**Comment by Techno3d** [comment]
Yea I like the compromise.

**Comment by rexmagnusdavid** [comment]
Unfortunately, the `minreq` crate is so lightweight that it doesn't support an easy way for retrying. I'd recommend using `reqwest` instead, since there's already a middleware and retry crate to accompany it.

**Comment by Techno3d** [comment]
Retry should not be hard to implement ourselves
and adding reqwest for that seems unnecessary as most of the features we won't use and it adds half a gig to dependencies

**Comment by rexmagnusdavid** [comment]
Fair point, I'm just being lazy. I'll just work on the `predict()` functions for now and wait for you to implement retries.
