### ISSUE TITLE
Confusing fallback value for bus departure time

### ISSUE THREAD

**Issue by rexmagnusdavid** [Techno3d/TransitArrivalBoard#5]
For `BusStopHandler`, we calculate the minutes until arrival with the expected departure time as listed in the SIRI struct. However, if an error occurs while unwrapping, the program currently sets the arrival time to the current time.

`let arrival_time = visit.monitored_vehicle_journey.monitored_call.expected_departure_time.unwrap_or(current_time.to_rfc3339());`

This can result in a bus with "0 minutes" appearing unsorted in the list, causing confusion. 

I have two solutions: Either hide the bus or predict the time for that vehicle only.

**Comment by Techno3d** [comment]
If no departure time is listed, the bus is waiting. Or at least should be.

**Comment by Techno3d** [comment]
You can't really predict anything about a bus without departure time. It might not have a scheduled route, which I would suspect to be the error. However, this issue doesn't affect the lines I think it would. It might be that they aren't using expected departure and just using arrival, but I find that dubious. I think we should just pass them.
